spring:
  application:
    name: wedding-backend
  datasource:
    url: jdbc:h2:mem:wedding;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: debug
    com.wedding.backend.query: debug
